#!/usr/bin/env bash
#=================================================================
# OmniTube by Scott Fleming
# scott@omnicommander.com
# Video Display application 
#=================================================================
# apt install bc

# stop vlc if it's running or frozen
pkill -9 vlc

# Load our vairables to be used -- 
source /home/pi/pi-tube/config.sh

echo "Running Fetch Application - v1.2a.023 by Scott Fleming" > $fetchLog

mkdir -p $VIDEOPATH
mkdir -p $JSONPATH


# clear vido directory of video files
echo "$TIMESTAMP Clearning $VIDEOPATH directory..." >> $fetchLog

for i in ${VIDEOPATH}/*
do
  echo "deleting ${i}" >> $fetchLog
  rm ${i}
done

echo "$TIMESTAMP Executing query for ${URL}${PI_UID}" >> $fetchLog
/usr/bin/curl -s -H "Content-Type: application/json" -X GET "$URL$PI_UID" -o $JSONPATH/file.json 

# use jq to parse array of json and load into arr
arr=( $(jq -r '.[].youtube_id' $JSONPATH/file.json ) )

# iterate array and issue youtube-dl command for the id
for i in "${!arr[@]}"
 
  do

    # compare if file exists, if not download it.
    # ===========================================
    
    FILE=$VIDEOPATH${i}_${PI_UID}_${arr[$i]}.mp4
    
    if [ ! -f "$FILE" ]; then
        
	    echo "$TIMESTAMP Executing youtube-dl: ${i}_${PI_UID}_${arr[$i]}.mp4..." >> $fetchLog
	    
        # download our video
        echo -ne " Executing youtube-dl: ${i}_${PI_UID}_${arr[$i]}.mp4...\r"

        youtube-dl --format mp4 --no-warnings --ignore-errors --ignore-config --prefer-ffmpeg https://www.youtube.com/watch?v=${arr[$i]} -o $VIDEOPATH/${i}_${PI_UID}_${arr[$i]}.mp4
    
    else
        echo "$FILE exists.. skipping"
        echo "$TIMESTAMP $FILE exists, no youtube-dl required." >> $fetchLog
    fi
   
done

echo "$TIMESTAMP run vlc" >> $fetchLog

# Run the looper script
exec /home/pi/pi-tube/looper 

exit 0;
