#!/usr/bin/env bash
#=================================================================
# OmniTube by Scott Fleming
# scott@omnicommander.com
# Video Display application 
#=================================================================

# Load our vairables to be used -- 
source /home/pi/pi-tube/config.sh

echo "$TIMESTAMP Running Fetch Application - v1.3 by Scott Fleming" >> $fetchLog

mkdir -p $VIDEOPATH
mkdir -p $JSONPATH

inventory=()

for file in ${VIDEOPATH}/*; do
  part="${file##*_}" # Use PE to get the id as the part after the last '.'
  vid="${part%.*}"
  inventory+=( "$vid" )
done

echo "$TIMESTAMP Current inventory IDs: ${inventory[@]}" >> $fetchLog


/usr/bin/curl -s -H "Content-Type: application/json" -X GET "$URL$PI_UID" -o $JSONPATH/file.json 

# use jq to parse array of json and load into arr
arr=( $(jq -r '.[].youtube_id' $JSONPATH/file.json ) )

echo "$TIMESTAMP IDs from host: ${arr[@]}" >> $fetchLog

# compare inventory with arr of youtubes we just got from server
diff=()
for i in "${arr[@]}"; do
    skip=
    for j in "${inventory[@]}"; do
        [[ $i == $j ]] && { skip=1; break; }
    done

    [[ -n $skip ]] || diff+=("$i")
done

echo "$TIMESTAMP Found differences: ${!diff[@]}" >> $fetchLog
echo "$TIMESTAMP count of inventory: ${!inventory[@]}" >> $fetchLog

# get our starting increment number
for counter in "${!inventory[@]}"; do 
    start=$counter
done
start=$(expr $start + 2)
echo "$TIMESTAMP Starting at $start" >> $fetchLog

# iterate diff array and issue youtube-dl command for the id's 
# 
for i in "${!diff[@]}" 
  do
           
        # download our video
        echo "$TIMESTAMP executed: youtube-dl: ${start}_${PI_UID}_${diff[$i]}.mp4 " >> $fetchLog

        youtube-dl --no-mtime --format mp4 --no-warnings --ignore-errors --ignore-config --prefer-ffmpeg https://www.youtube.com/watch?v=${diff[$i]} -o $VIDEOPATH/${start}_${PI_UID}_${diff[$i]}.mp4

        # increment counter 
        start=$(expr $start + 1)
   
done

# compare when finished to clean up files which are no longer in arr.
# ===================================================================

Array3=()
for i in "${inventory[@]}"; do
    skip=
    for j in "${arr[@]}"; do
        [[ $i == $j ]] && { skip=1; break; }
    done
    [[ -n $skip ]] || Array3+=("$i")
done

# Iterate Array3 and remove these files
for d in "${Array3[@]}"; do
    echo "$TIMESTAMP deleteing ${VIDEOPATH}/ like *${d}*" >> $fetchLog
    find "${VIDEOPATH}/" -name "*${d}*" -type f -exec rm {} +
done


# stop vlc if it's running or frozen
echo "$TIMESTAMP killing VLC" >> $fetchLog

pkill -9 vlc

# Run the looper script
echo "$TIMESTAMP run vlc" >> $fetchLog
exec /home/pi/pi-tube/looper 

echo "$TIMESTAMP exit fetch" >> $fetchLog
exit 0;
