#!/usr/bin/env bash
# OmniTube v1.0 -- Scott Fleming
# scott@omnicommander.com
# ================================================================
source /home/pi/pi-tube/config.sh
# get rid of the cursor so we don't see it when videos are running

#title="omnitube by scott fleming v2.0"

 # VLC option parameters
 # ================================================================
        # -Z : Look in the $VIDEOPATH directory and play all files
        # -L : Loop the list of files 
        # -f : play video full screen always
	# -q : quiet - disable errors, warnings etc.
	# -d : run as daemon service 
        # --no-video-title-show : Do not display the video title
        # --no-random : Play in the order they are listed in the directory
	# --no-audio : Do not play audio
        # =================================================================
        # sub-source parameters: 
        # position: {0 (Center), 1 (Left), 2 (Right), 4 (Top), 8 (Bottom), 5 (Top-Left), 6 (Top-Right), 9 (Bottom-Left), 10 (Bottom-Right)} 
        # x: horizontal spacing y: vertical spacing
        # color: 0xhex-value color HTML #000000 = black, #FF0000 = red, #00FF00 = green, #FFFF00 = yellow (red + green), #FFFFFF = white
        # opacity: 0=transparent 255=opaque (default)

echo "$TIMESTAMP Running cvlc $VIDEOPATH $TITLE" >> $fetchLog

cvlc -ZLfqd $VIDEOPATH --no-video-title-show --no-random  --no-audio --sub-source="marq{marquee=$TITLE  %a %b %d %Y %l:%M:%S %P,color=0xFFFFFF,position=10,size=16,x=20,y=10}:logo{file=$LOGOPATH, position=6,x=10,opacity=100}"

echo "$TIMESTAMP Looper is running as daemon and I'm done.">> $fetchLog

