#!/usr/bin/env bash
tempC=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
tempF=$(echo "scale=2; 1.8 *$tempC + 32" | bc)

X=($tempC, $tempF)

printf '%s\n' "${X[@]}" | jq -R . | jq -s .

#curl -d "$jsonny" -H "Content-Type: application/json" -X POST http://34.193.150.151/dat-receive.php
